name: Publish to the Visual Studio Marketplace
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript to JavaScript
        run: npm run compile

      - name: Build Extension Package
        run: npm run package

      - name: Publish Extension Package on the Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run publish
